{% set name = "lark" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lark-{{ version }}.tar.gz
  sha256: 7da76fcfddadabbbbfd949bbae221efd33938451d90b1fefbbc423c3cccf48ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]
    
requirements:
  host:
    - pip
    - python
    - setuptools
    - regex
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - lark
  commands:
    - pip check
    # Skipping tests/test_nearley because the sdist is missing some test data files.
    - pytest -v tests --ignore tests/test_nearley  # [py>=310]
    - pytest -v tests --ignore tests/test_nearley --ignore tests/test_pattern_matching.py  # [py<310]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lark-parser/lark
  summary: Lark is a parsing toolkit for Python, built with a focus on ergonomics, performance and modularity.
  description: |
    Lark is a parsing toolkit for Python, built with a focus on ergonomics, performance and modularity.

    Lark can parse all context-free languages. To put it simply, it means that it is capable of parsing almost any programming language out there, and to some degree most natural languages too.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/lark-parser/lark
  doc_url: https://lark-parser.readthedocs.io

extra:
  recipe-maintainers:
    - BastianZim
