{% set name = "lark" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lark-{{ version }}.tar.gz
  sha256: 7a8d0c07d663da9391d7faee1bf1d7df4998c47ca43a593cbef5c7566acd057a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<36]
    
requirements:
  host:
    - regex
    - pip
    - python >=3.6
  run:
    - atomicwrites
    - js2py
    - python >=3.6
    - regex
    - js2py

test:
  imports:
    - lark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lark-parser/lark
  summary: a modern parsing library
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/lark-parser/lark

extra:
  recipe-maintainers:
    - BastianZim
