{% set name = "lark" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lark-{{ version }}.tar.gz
  sha256: 5115193433051f079374c4f81059fa4bf2afa78cc87dd87817ed4435e8647c82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - regex
    - pip
    - python >=3.6
  run:
    - atomicwrites
    - js2py
    - python >=3.6
    - regex

test:
  imports:
    - lark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lark-parser/lark
  summary: a modern parsing library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
