{% set name = "lark" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b426a7a6d6d53189d318f2b6236ab5d6429eaf09259f1ca33eb716eed10d2905

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=80
    - setuptools-scm >=9.2.2
  run:
    - python
  run_constrained:
    - interegular >=0.3.1,<0.4.0

test:
  source_files:
    - tests
  imports:
    - lark
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Skipping tests/test_nearley because the sdist is missing some test data files.
    - pytest -v tests --ignore tests/test_nearley  # [py>=310]
    - pytest -v tests --ignore tests/test_nearley --ignore tests/test_pattern_matching.py  # [py<310]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lark-parser/lark
  summary: Lark is a parsing toolkit for Python, built with a focus on ergonomics, performance and modularity.
  description: |
    Lark is a parsing toolkit for Python, built with a focus on ergonomics, performance and modularity.

    Lark can parse all context-free languages. To put it simply, it means that it is capable of parsing almost any programming language out there, and to some degree most natural languages too.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/lark-parser/lark
  doc_url: https://lark-parser.readthedocs.io

extra:
  recipe-maintainers:
    - BastianZim
